/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CafeController;
import java.awt.geom.RoundRectangle2D;
import model.CafeModel;

/**
 *
 * @author krish
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        roundCorners();
    }
    private void roundCorners(){
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 25, 25));   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblFirstName2 = new javax.swing.JLabel();
        lblFirstName3 = new javax.swing.JLabel();
        btnUserLogin = new view.Buttons();
        btnUserSignup = new view.Buttons();
        txtLoginUsername = new view.TextField();
        passwordField1 = new view.PasswordField();
        buttons1 = new view.Buttons();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(27, 31, 43));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(32, 37, 53));

        lblLogin.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(235, 87, 87));
        lblLogin.setText("LOGIN");

        lblFirstName2.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        lblFirstName2.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName2.setText("Username");

        lblFirstName3.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        lblFirstName3.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName3.setText("Password");

        btnUserLogin.setBackground(new java.awt.Color(235, 87, 87));
        btnUserLogin.setBorder(null);
        btnUserLogin.setForeground(new java.awt.Color(27, 31, 43));
        btnUserLogin.setText("Login");
        btnUserLogin.setBorderColor(new java.awt.Color(32, 37, 53));
        btnUserLogin.setColor(new java.awt.Color(235, 87, 87));
        btnUserLogin.setColorClick(new java.awt.Color(231, 54, 54));
        btnUserLogin.setColorOver(new java.awt.Color(238, 118, 118));
        btnUserLogin.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnUserLogin.setRadius(25);
        btnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLoginActionPerformed(evt);
            }
        });

        btnUserSignup.setBackground(new java.awt.Color(37, 42, 61));
        btnUserSignup.setBorder(null);
        btnUserSignup.setForeground(new java.awt.Color(235, 87, 87));
        btnUserSignup.setText("Sign Up");
        btnUserSignup.setBorderColor(new java.awt.Color(32, 37, 53));
        btnUserSignup.setColor(new java.awt.Color(37, 42, 61));
        btnUserSignup.setColorClick(new java.awt.Color(25, 28, 41));
        btnUserSignup.setColorOver(new java.awt.Color(44, 50, 73));
        btnUserSignup.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnUserSignup.setRadius(25);
        btnUserSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSignupActionPerformed(evt);
            }
        });

        txtLoginUsername.setBackground(new java.awt.Color(27, 31, 43));
        txtLoginUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtLoginUsername.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        txtLoginUsername.setRound(25);

        passwordField1.setBackground(new java.awt.Color(27, 31, 43));
        passwordField1.setForeground(new java.awt.Color(255, 255, 255));
        passwordField1.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        passwordField1.setRound(25);

        buttons1.setBackground(new java.awt.Color(235, 87, 87));
        buttons1.setBorder(null);
        buttons1.setText("X");
        buttons1.setBorderColor(new java.awt.Color(32, 37, 53));
        buttons1.setColor(new java.awt.Color(235, 87, 87));
        buttons1.setColorClick(new java.awt.Color(231, 54, 54));
        buttons1.setColorOver(new java.awt.Color(238, 118, 118));
        buttons1.setFont(new java.awt.Font("Google Sans Medium", 0, 12)); // NOI18N
        buttons1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttons1.setRadius(20);
        buttons1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttons1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstName3)
                    .addComponent(lblFirstName2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogin)
                        .addGap(127, 127, 127)
                        .addComponent(buttons1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passwordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(btnUserSignup, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(btnUserLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttons1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblFirstName2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFirstName3)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUserSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSignupActionPerformed
        dispose();
        SignupForm signup = new SignupForm();
        signup.setVisible(true);
    }//GEN-LAST:event_btnUserSignupActionPerformed

    private void btnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLoginActionPerformed
        CafeModel Loginobj = new CafeModel(); 
        Loginobj.setuName(txtLoginUsername.getText());
        Loginobj.setPassword(passwordField1.getText());
        
        CafeController cC = new CafeController();
        cC.getfromDB(Loginobj);

    }//GEN-LAST:event_btnUserLoginActionPerformed

    private void buttons1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttons1ActionPerformed
        dispose();
    }//GEN-LAST:event_buttons1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */ 
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.Buttons btnUserLogin;
    private view.Buttons btnUserSignup;
    private view.Buttons buttons1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFirstName2;
    private javax.swing.JLabel lblFirstName3;
    private javax.swing.JLabel lblLogin;
    private view.PasswordField passwordField1;
    private view.TextField txtLoginUsername;
    // End of variables declaration//GEN-END:variables
}
