/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;



import controller.CafeController;

import java.awt.Color;
import java.awt.Font;
import java.awt.geom.RoundRectangle2D;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.CafeModel;
import Designs.TableCustom;
import controller.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author krish
 */
public final class MainForm extends javax.swing.JFrame {
    
    public MainForm() {
        initComponents();
        roundCorners();
        TableCustom.apply(jScrollPane1, TableCustom.TableType.DEFAULT);
        curDate();
        viewHistryTbl();
        viewFdTbl();
        viewBvTbl();
        customTable();
        setBillNo();
        
    }
    
    public void cal(){
        
        CafeModel tblObj = new CafeModel();
        tblObj.setTblOrder(tblOrder);
        tblObj.setLblTot(lblTot);
        
        CafeController cC = new CafeController();
        cC.cal(tblObj);
    
    }
    
    public void addTable(String name,int qty,double price,double amount){
        
        CafeModel tblAddObj = new CafeModel();
        tblAddObj.setName(name);
        tblAddObj.setQty(qty);
        tblAddObj.setPrice(price);
        tblAddObj.setAmount(amount);
        tblAddObj.setTblOrder(tblOrder);
        
        CafeController cCt = new CafeController();
        cCt.addTable(tblAddObj);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        btnLogout = new view.Buttons();
        lblUsername = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnUpdates = new view.Buttons();
        btnMenu = new view.Buttons();
        btnHistory = new view.Buttons();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblBillNo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lblTot = new javax.swing.JLabel();
        btnItmsClear = new view.Buttons();
        btnItmDelete = new view.Buttons();
        lblBalancetxt = new javax.swing.JLabel();
        lblCash1 = new javax.swing.JLabel();
        lblBalance1 = new javax.swing.JLabel();
        btnPlaceOrder = new view.Buttons();
        txtCash = new view.TextField();
        jPanel12 = new javax.swing.JPanel();
        btnBeverage = new view.Buttons();
        btnFood = new view.Buttons();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        q1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblFood = new javax.swing.JLabel();
        btnHtDg1 = new view.Buttons();
        q2 = new javax.swing.JLabel();
        btnHtDg2 = new view.Buttons();
        q3 = new javax.swing.JLabel();
        btnHtDg3 = new view.Buttons();
        jLabel1 = new javax.swing.JLabel();
        q4 = new javax.swing.JLabel();
        btnHtDg4 = new view.Buttons();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        q5 = new javax.swing.JLabel();
        btnBrgr1 = new view.Buttons();
        q6 = new javax.swing.JLabel();
        btnBrgr2 = new view.Buttons();
        q7 = new javax.swing.JLabel();
        btnBrgr3 = new view.Buttons();
        q8 = new javax.swing.JLabel();
        btnBrgr4 = new view.Buttons();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        q9 = new javax.swing.JLabel();
        q10 = new javax.swing.JLabel();
        q11 = new javax.swing.JLabel();
        btnSbmrn1 = new view.Buttons();
        btnSbmrn2 = new view.Buttons();
        btnSbmrn3 = new view.Buttons();
        jPanel11 = new javax.swing.JPanel();
        lblBeverage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        q12 = new javax.swing.JLabel();
        btnHt1 = new view.Buttons();
        q13 = new javax.swing.JLabel();
        btnHt2 = new view.Buttons();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        q14 = new javax.swing.JLabel();
        btnCl1 = new view.Buttons();
        q15 = new javax.swing.JLabel();
        btnCl2 = new view.Buttons();
        q16 = new javax.swing.JLabel();
        btnCl3 = new view.Buttons();
        q17 = new javax.swing.JLabel();
        btnCl4 = new view.Buttons();
        q18 = new javax.swing.JLabel();
        btnCl5 = new view.Buttons();
        q19 = new javax.swing.JLabel();
        btnCl6 = new view.Buttons();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        lblFood1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBvrg = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtUpdtPrice = new view.TextField();
        txtUpdtName = new view.TextField();
        btnUpdate = new view.Buttons();
        txtUpdtID = new view.TextField();
        jLabel18 = new javax.swing.JLabel();
        txtSrchBv = new view.TextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFd = new javax.swing.JTable();
        txtSrchfd1 = new view.TextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(996, 712));
        setMinimumSize(new java.awt.Dimension(996, 712));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(996, 712));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(37, 42, 61));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setBackground(new java.awt.Color(32, 37, 53));
        btnLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(235, 87, 87), 1, true));
        btnLogout.setForeground(new java.awt.Color(235, 87, 87));
        btnLogout.setText("Logout");
        btnLogout.setBorderColor(new java.awt.Color(37, 42, 61));
        btnLogout.setBorderPainted(false);
        btnLogout.setColor(new java.awt.Color(32, 37, 53));
        btnLogout.setColorClick(new java.awt.Color(235, 87, 87));
        btnLogout.setColorOver(new java.awt.Color(27, 31, 43));
        btnLogout.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnLogout.setRadius(25);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel6.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 90, 40));

        lblUsername.setFont(new java.awt.Font("ITC Avant Garde Gothic LT", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Cafe 96");
        jPanel6.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 100, 60));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 320, 60));

        jPanel5.setBackground(new java.awt.Color(32, 37, 53));
        jPanel5.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdates.setBackground(new java.awt.Color(32, 37, 53));
        btnUpdates.setBorder(null);
        btnUpdates.setForeground(new java.awt.Color(204, 204, 204));
        btnUpdates.setText("Updates");
        btnUpdates.setBorderColor(new java.awt.Color(32, 37, 53));
        btnUpdates.setColor(new java.awt.Color(32, 37, 53));
        btnUpdates.setColorClick(new java.awt.Color(235, 87, 87));
        btnUpdates.setColorOver(new java.awt.Color(27, 31, 43));
        btnUpdates.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnUpdates.setRadius(25);
        btnUpdates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatesActionPerformed(evt);
            }
        });
        jPanel5.add(btnUpdates, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 100, 40));

        btnMenu.setBackground(new java.awt.Color(32, 37, 53));
        btnMenu.setBorder(null);
        btnMenu.setForeground(new java.awt.Color(204, 204, 204));
        btnMenu.setText("Menu");
        btnMenu.setBorderColor(new java.awt.Color(32, 37, 53));
        btnMenu.setColor(new java.awt.Color(32, 37, 53));
        btnMenu.setColorClick(new java.awt.Color(235, 87, 87));
        btnMenu.setColorOver(new java.awt.Color(27, 31, 43));
        btnMenu.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnMenu.setRadius(25);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel5.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 40));

        btnHistory.setBorder(null);
        btnHistory.setForeground(new java.awt.Color(204, 204, 204));
        btnHistory.setText("History");
        btnHistory.setBorderColor(new java.awt.Color(32, 37, 53));
        btnHistory.setColor(new java.awt.Color(32, 37, 53));
        btnHistory.setColorClick(new java.awt.Color(235, 87, 87));
        btnHistory.setColorOver(new java.awt.Color(27, 31, 43));
        btnHistory.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnHistory.setRadius(25);
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        jPanel5.add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 100, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 60));

        jTabbedPane1.setBackground(new java.awt.Color(27, 31, 43));

        jPanel2.setBackground(new java.awt.Color(27, 31, 43));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");
        jPanel2.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 87, 87));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 12));

        jPanel9.setBackground(new java.awt.Color(37, 42, 61));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(37, 42, 61));
        jPanel13.setAutoscrolls(true);

        lblDate.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(204, 204, 204));
        lblDate.setText("(Date)");

        jLabel10.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Bill No.");

        lblBillNo.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        lblBillNo.setForeground(new java.awt.Color(204, 204, 204));
        lblBillNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBillNo.setText("0");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(jLabel10)
                    .addComponent(lblBillNo))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 320, 60));

        tblOrder.setBackground(new java.awt.Color(37, 42, 61));
        tblOrder.setFont(new java.awt.Font("Google Sans Medium", 0, 10)); // NOI18N
        tblOrder.setForeground(new java.awt.Color(255, 255, 255));
        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Qty", "Price", "Amount"
            }
        ));
        tblOrder.setFocusable(false);
        tblOrder.setGridColor(new java.awt.Color(204, 204, 204));
        tblOrder.setRowHeight(25);
        tblOrder.setSelectionBackground(new java.awt.Color(235, 87, 87));
        tblOrder.setSelectionForeground(new java.awt.Color(37, 42, 61));
        tblOrder.setShowHorizontalLines(true);
        tblOrder.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblOrder);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 300, 270));

        lblTotal.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total");
        jPanel9.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 150, 40));
        jPanel9.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 280, 10));
        jPanel9.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 280, 20));

        lblTot.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        lblTot.setForeground(new java.awt.Color(235, 87, 87));
        lblTot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTot.setText("0.00");
        lblTot.setToolTipText("");
        lblTot.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblTot.setRequestFocusEnabled(false);
        jPanel9.add(lblTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 130, 40));

        btnItmsClear.setBackground(new java.awt.Color(32, 37, 53));
        btnItmsClear.setBorder(null);
        btnItmsClear.setForeground(new java.awt.Color(255, 255, 255));
        btnItmsClear.setText("Clear");
        btnItmsClear.setBorderColor(new java.awt.Color(44, 50, 73));
        btnItmsClear.setBorderPainted(false);
        btnItmsClear.setColor(new java.awt.Color(32, 37, 53));
        btnItmsClear.setColorClick(new java.awt.Color(27, 31, 43));
        btnItmsClear.setColorOver(new java.awt.Color(44, 50, 73));
        btnItmsClear.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnItmsClear.setRadius(20);
        btnItmsClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItmsClearActionPerformed(evt);
            }
        });
        jPanel9.add(btnItmsClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 135, 40));

        btnItmDelete.setBackground(new java.awt.Color(32, 37, 53));
        btnItmDelete.setBorder(null);
        btnItmDelete.setForeground(new java.awt.Color(235, 87, 87));
        btnItmDelete.setText("Delete");
        btnItmDelete.setBorderColor(new java.awt.Color(44, 50, 73));
        btnItmDelete.setBorderPainted(false);
        btnItmDelete.setColor(new java.awt.Color(32, 37, 53));
        btnItmDelete.setColorClick(new java.awt.Color(27, 31, 43));
        btnItmDelete.setColorOver(new java.awt.Color(44, 50, 73));
        btnItmDelete.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnItmDelete.setRadius(20);
        btnItmDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItmDeleteActionPerformed(evt);
            }
        });
        jPanel9.add(btnItmDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 135, 40));

        lblBalancetxt.setFont(new java.awt.Font("Google Sans Medium", 0, 16)); // NOI18N
        lblBalancetxt.setForeground(new java.awt.Color(204, 204, 204));
        lblBalancetxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBalancetxt.setText("0.00");
        jPanel9.add(lblBalancetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 160, 30));

        lblCash1.setFont(new java.awt.Font("Google Sans Medium", 0, 16)); // NOI18N
        lblCash1.setForeground(new java.awt.Color(204, 204, 204));
        lblCash1.setText("Cash          :");
        jPanel9.add(lblCash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, 30));

        lblBalance1.setFont(new java.awt.Font("Google Sans Medium", 0, 16)); // NOI18N
        lblBalance1.setForeground(new java.awt.Color(204, 204, 204));
        lblBalance1.setText("Balance     :");
        jPanel9.add(lblBalance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, 30));

        btnPlaceOrder.setBackground(new java.awt.Color(235, 87, 87));
        btnPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setText("PAY");
        btnPlaceOrder.setBorderColor(new java.awt.Color(37, 42, 61));
        btnPlaceOrder.setColor(new java.awt.Color(235, 87, 87));
        btnPlaceOrder.setColorClick(new java.awt.Color(255, 30, 30));
        btnPlaceOrder.setColorOver(new java.awt.Color(238, 113, 113));
        btnPlaceOrder.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        btnPlaceOrder.setRadius(25);
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        jPanel9.add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 280, 50));

        txtCash.setBackground(new java.awt.Color(27, 31, 43));
        txtCash.setForeground(new java.awt.Color(255, 255, 255));
        txtCash.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCash.setFont(new java.awt.Font("Google Sans Medium", 0, 16)); // NOI18N
        txtCash.setRound(25);
        jPanel9.add(txtCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 170, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 320, 660));

        jPanel12.setBackground(new java.awt.Color(27, 31, 43));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBeverage.setBorder(null);
        btnBeverage.setForeground(new java.awt.Color(204, 204, 204));
        btnBeverage.setText("Beverage");
        btnBeverage.setBorderColor(new java.awt.Color(27, 31, 43));
        btnBeverage.setColor(new java.awt.Color(32, 37, 53));
        btnBeverage.setColorClick(new java.awt.Color(235, 87, 87));
        btnBeverage.setColorOver(new java.awt.Color(44, 50, 73));
        btnBeverage.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnBeverage.setRadius(25);
        btnBeverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeverageActionPerformed(evt);
            }
        });
        jPanel12.add(btnBeverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 100, 40));

        btnFood.setBorder(null);
        btnFood.setForeground(new java.awt.Color(204, 204, 204));
        btnFood.setText("Food");
        btnFood.setBorderColor(new java.awt.Color(235, 87, 87));
        btnFood.setBorderPainted(false);
        btnFood.setColor(new java.awt.Color(32, 37, 53));
        btnFood.setColorClick(new java.awt.Color(235, 87, 87));
        btnFood.setColorOver(new java.awt.Color(44, 50, 73));
        btnFood.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnFood.setRadius(25);
        btnFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoodActionPerformed(evt);
            }
        });
        jPanel12.add(btnFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 100, 40));

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 70));

        jTabbedPane2.setBackground(new java.awt.Color(27, 31, 43));

        jPanel10.setBackground(new java.awt.Color(27, 31, 43));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        q1.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q1.setForeground(new java.awt.Color(235, 87, 87));
        q1.setText("0");
        jPanel10.add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 20, -1));
        jPanel10.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 610, 10));

        lblFood.setFont(new java.awt.Font("Google Sans Medium", 0, 24)); // NOI18N
        lblFood.setForeground(new java.awt.Color(235, 87, 87));
        lblFood.setText("Foods");
        jPanel10.add(lblFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 40));

        btnHtDg1.setBackground(new java.awt.Color(37, 42, 61));
        btnHtDg1.setBorder(null);
        btnHtDg1.setForeground(new java.awt.Color(255, 255, 255));
        btnHtDg1.setText("Chicken");
        btnHtDg1.setBorderColor(new java.awt.Color(27, 31, 43));
        btnHtDg1.setColor(new java.awt.Color(37, 42, 61));
        btnHtDg1.setColorClick(new java.awt.Color(235, 87, 87));
        btnHtDg1.setColorOver(new java.awt.Color(44, 50, 73));
        btnHtDg1.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnHtDg1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHtDg1.setRadius(25);
        btnHtDg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHtDg1ActionPerformed(evt);
            }
        });
        jPanel10.add(btnHtDg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 60));

        q2.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q2.setForeground(new java.awt.Color(235, 87, 87));
        q2.setText("0");
        jPanel10.add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 20, -1));

        btnHtDg2.setBackground(new java.awt.Color(37, 42, 61));
        btnHtDg2.setBorder(null);
        btnHtDg2.setForeground(new java.awt.Color(255, 255, 255));
        btnHtDg2.setText("Egg Wrapped");
        btnHtDg2.setBorderColor(new java.awt.Color(27, 31, 43));
        btnHtDg2.setColor(new java.awt.Color(37, 42, 61));
        btnHtDg2.setColorClick(new java.awt.Color(235, 87, 87));
        btnHtDg2.setColorOver(new java.awt.Color(44, 50, 73));
        btnHtDg2.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnHtDg2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHtDg2.setRadius(25);
        btnHtDg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHtDg2ActionPerformed(evt);
            }
        });
        jPanel10.add(btnHtDg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 150, 60));

        q3.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q3.setForeground(new java.awt.Color(235, 87, 87));
        q3.setText("0");
        jPanel10.add(q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 20, -1));

        btnHtDg3.setBackground(new java.awt.Color(37, 42, 61));
        btnHtDg3.setBorder(null);
        btnHtDg3.setForeground(new java.awt.Color(255, 255, 255));
        btnHtDg3.setText("Monster Double");
        btnHtDg3.setBorderColor(new java.awt.Color(27, 31, 43));
        btnHtDg3.setColor(new java.awt.Color(37, 42, 61));
        btnHtDg3.setColorClick(new java.awt.Color(235, 87, 87));
        btnHtDg3.setColorOver(new java.awt.Color(44, 50, 73));
        btnHtDg3.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnHtDg3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHtDg3.setRadius(25);
        btnHtDg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHtDg3ActionPerformed(evt);
            }
        });
        jPanel10.add(btnHtDg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 150, 60));

        jLabel1.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hot Dogs");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 86, 120, 30));

        q4.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q4.setForeground(new java.awt.Color(235, 87, 87));
        q4.setText("0");
        jPanel10.add(q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 20, -1));

        btnHtDg4.setBackground(new java.awt.Color(37, 42, 61));
        btnHtDg4.setBorder(null);
        btnHtDg4.setForeground(new java.awt.Color(255, 255, 255));
        btnHtDg4.setText("Cheesy Chicken");
        btnHtDg4.setBorderColor(new java.awt.Color(27, 31, 43));
        btnHtDg4.setColor(new java.awt.Color(37, 42, 61));
        btnHtDg4.setColorClick(new java.awt.Color(235, 87, 87));
        btnHtDg4.setColorOver(new java.awt.Color(44, 50, 73));
        btnHtDg4.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnHtDg4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHtDg4.setRadius(25);
        btnHtDg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHtDg4ActionPerformed(evt);
            }
        });
        jPanel10.add(btnHtDg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 160, 60));
        jPanel10.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 610, 10));

        jLabel2.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Burgers");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, 30));

        q5.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q5.setForeground(new java.awt.Color(235, 87, 87));
        q5.setText("0");
        jPanel10.add(q5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 20, -1));

        btnBrgr1.setBackground(new java.awt.Color(37, 42, 61));
        btnBrgr1.setBorder(null);
        btnBrgr1.setForeground(new java.awt.Color(255, 255, 255));
        btnBrgr1.setText("Vegetable");
        btnBrgr1.setBorderColor(new java.awt.Color(27, 31, 43));
        btnBrgr1.setColor(new java.awt.Color(37, 42, 61));
        btnBrgr1.setColorClick(new java.awt.Color(235, 87, 87));
        btnBrgr1.setColorOver(new java.awt.Color(44, 50, 73));
        btnBrgr1.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnBrgr1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBrgr1.setRadius(25);
        btnBrgr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrgr1ActionPerformed(evt);
            }
        });
        jPanel10.add(btnBrgr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 110, 60));

        q6.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q6.setForeground(new java.awt.Color(235, 87, 87));
        q6.setText("0");
        jPanel10.add(q6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 20, -1));

        btnBrgr2.setBackground(new java.awt.Color(37, 42, 61));
        btnBrgr2.setBorder(null);
        btnBrgr2.setForeground(new java.awt.Color(255, 255, 255));
        btnBrgr2.setText("Cheesy Vegetable");
        btnBrgr2.setBorderColor(new java.awt.Color(27, 31, 43));
        btnBrgr2.setColor(new java.awt.Color(37, 42, 61));
        btnBrgr2.setColorClick(new java.awt.Color(235, 87, 87));
        btnBrgr2.setColorOver(new java.awt.Color(44, 50, 73));
        btnBrgr2.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnBrgr2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBrgr2.setRadius(25);
        btnBrgr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrgr2ActionPerformed(evt);
            }
        });
        jPanel10.add(btnBrgr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 160, 60));

        q7.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q7.setForeground(new java.awt.Color(235, 87, 87));
        q7.setText("0");
        jPanel10.add(q7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 20, -1));

        btnBrgr3.setBackground(new java.awt.Color(37, 42, 61));
        btnBrgr3.setBorder(null);
        btnBrgr3.setForeground(new java.awt.Color(255, 255, 255));
        btnBrgr3.setText("Spicy Chicken");
        btnBrgr3.setBorderColor(new java.awt.Color(27, 31, 43));
        btnBrgr3.setColor(new java.awt.Color(37, 42, 61));
        btnBrgr3.setColorClick(new java.awt.Color(235, 87, 87));
        btnBrgr3.setColorOver(new java.awt.Color(44, 50, 73));
        btnBrgr3.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnBrgr3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBrgr3.setRadius(25);
        btnBrgr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrgr3ActionPerformed(evt);
            }
        });
        jPanel10.add(btnBrgr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 140, 60));

        q8.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q8.setForeground(new java.awt.Color(235, 87, 87));
        q8.setText("0");
        jPanel10.add(q8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 20, -1));

        btnBrgr4.setBackground(new java.awt.Color(37, 42, 61));
        btnBrgr4.setBorder(null);
        btnBrgr4.setForeground(new java.awt.Color(255, 255, 255));
        btnBrgr4.setText("Cheesy Crispy Chicken");
        btnBrgr4.setBorderColor(new java.awt.Color(27, 31, 43));
        btnBrgr4.setColor(new java.awt.Color(37, 42, 61));
        btnBrgr4.setColorClick(new java.awt.Color(235, 87, 87));
        btnBrgr4.setColorOver(new java.awt.Color(44, 50, 73));
        btnBrgr4.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnBrgr4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBrgr4.setRadius(25);
        btnBrgr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrgr4ActionPerformed(evt);
            }
        });
        jPanel10.add(btnBrgr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 170, 60));

        jLabel3.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Submarines");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 120, 30));
        jPanel10.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 610, 10));

        q9.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q9.setForeground(new java.awt.Color(235, 87, 87));
        q9.setText("0");
        jPanel10.add(q9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 20, -1));

        q10.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q10.setForeground(new java.awt.Color(235, 87, 87));
        q10.setText("0");
        jPanel10.add(q10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 20, -1));

        q11.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q11.setForeground(new java.awt.Color(235, 87, 87));
        q11.setText("0");
        jPanel10.add(q11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 20, -1));

        btnSbmrn1.setBackground(new java.awt.Color(37, 42, 61));
        btnSbmrn1.setBorder(null);
        btnSbmrn1.setForeground(new java.awt.Color(255, 255, 255));
        btnSbmrn1.setText("Vegetable");
        btnSbmrn1.setBorderColor(new java.awt.Color(27, 31, 43));
        btnSbmrn1.setColor(new java.awt.Color(37, 42, 61));
        btnSbmrn1.setColorClick(new java.awt.Color(235, 87, 87));
        btnSbmrn1.setColorOver(new java.awt.Color(44, 50, 73));
        btnSbmrn1.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnSbmrn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSbmrn1.setRadius(25);
        btnSbmrn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSbmrn1ActionPerformed(evt);
            }
        });
        jPanel10.add(btnSbmrn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 120, 60));

        btnSbmrn2.setBackground(new java.awt.Color(37, 42, 61));
        btnSbmrn2.setBorder(null);
        btnSbmrn2.setForeground(new java.awt.Color(255, 255, 255));
        btnSbmrn2.setText("Spicy");
        btnSbmrn2.setBorderColor(new java.awt.Color(27, 31, 43));
        btnSbmrn2.setColor(new java.awt.Color(37, 42, 61));
        btnSbmrn2.setColorClick(new java.awt.Color(235, 87, 87));
        btnSbmrn2.setColorOver(new java.awt.Color(44, 50, 73));
        btnSbmrn2.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnSbmrn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSbmrn2.setRadius(25);
        btnSbmrn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSbmrn2ActionPerformed(evt);
            }
        });
        jPanel10.add(btnSbmrn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 100, 60));

        btnSbmrn3.setBackground(new java.awt.Color(37, 42, 61));
        btnSbmrn3.setBorder(null);
        btnSbmrn3.setForeground(new java.awt.Color(255, 255, 255));
        btnSbmrn3.setText("Cheesy Crispy Chicken");
        btnSbmrn3.setBorderColor(new java.awt.Color(27, 31, 43));
        btnSbmrn3.setColor(new java.awt.Color(37, 42, 61));
        btnSbmrn3.setColorClick(new java.awt.Color(235, 87, 87));
        btnSbmrn3.setColorOver(new java.awt.Color(44, 50, 73));
        btnSbmrn3.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnSbmrn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSbmrn3.setRadius(25);
        btnSbmrn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSbmrn3ActionPerformed(evt);
            }
        });
        jPanel10.add(btnSbmrn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 210, 60));

        jTabbedPane2.addTab("tab1", jPanel10);

        jPanel11.setBackground(new java.awt.Color(27, 31, 43));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBeverage.setFont(new java.awt.Font("Google Sans Medium", 0, 24)); // NOI18N
        lblBeverage.setForeground(new java.awt.Color(235, 87, 87));
        lblBeverage.setText("Beverages");
        jPanel11.add(lblBeverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 60));

        jLabel4.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hot");
        jPanel11.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 86, 120, 30));
        jPanel11.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 610, 10));

        q12.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q12.setForeground(new java.awt.Color(235, 87, 87));
        q12.setText("0");
        jPanel11.add(q12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 20, -1));

        btnHt1.setBackground(new java.awt.Color(37, 42, 61));
        btnHt1.setBorder(null);
        btnHt1.setForeground(new java.awt.Color(255, 255, 255));
        btnHt1.setText("Milo");
        btnHt1.setBorderColor(new java.awt.Color(27, 31, 43));
        btnHt1.setColor(new java.awt.Color(37, 42, 61));
        btnHt1.setColorClick(new java.awt.Color(235, 87, 87));
        btnHt1.setColorOver(new java.awt.Color(44, 50, 73));
        btnHt1.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnHt1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHt1.setRadius(25);
        btnHt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHt1ActionPerformed(evt);
            }
        });
        jPanel11.add(btnHt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 60));

        q13.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q13.setForeground(new java.awt.Color(235, 87, 87));
        q13.setText("0");
        jPanel11.add(q13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 20, -1));

        btnHt2.setBackground(new java.awt.Color(37, 42, 61));
        btnHt2.setBorder(null);
        btnHt2.setForeground(new java.awt.Color(255, 255, 255));
        btnHt2.setText("Nescafe");
        btnHt2.setBorderColor(new java.awt.Color(27, 31, 43));
        btnHt2.setColor(new java.awt.Color(37, 42, 61));
        btnHt2.setColorClick(new java.awt.Color(235, 87, 87));
        btnHt2.setColorOver(new java.awt.Color(44, 50, 73));
        btnHt2.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnHt2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHt2.setRadius(25);
        btnHt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHt2ActionPerformed(evt);
            }
        });
        jPanel11.add(btnHt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 130, 60));
        jPanel11.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 610, 10));

        jLabel5.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cool");
        jPanel11.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, 30));

        q14.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q14.setForeground(new java.awt.Color(235, 87, 87));
        q14.setText("0");
        jPanel11.add(q14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 20, -1));

        btnCl1.setBackground(new java.awt.Color(37, 42, 61));
        btnCl1.setBorder(null);
        btnCl1.setForeground(new java.awt.Color(255, 255, 255));
        btnCl1.setText("Orange Juice");
        btnCl1.setBorderColor(new java.awt.Color(27, 31, 43));
        btnCl1.setColor(new java.awt.Color(37, 42, 61));
        btnCl1.setColorClick(new java.awt.Color(235, 87, 87));
        btnCl1.setColorOver(new java.awt.Color(44, 50, 73));
        btnCl1.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnCl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCl1.setRadius(25);
        btnCl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCl1ActionPerformed(evt);
            }
        });
        jPanel11.add(btnCl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 60));

        q15.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q15.setForeground(new java.awt.Color(235, 87, 87));
        q15.setText("0");
        jPanel11.add(q15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 20, -1));

        btnCl2.setBackground(new java.awt.Color(37, 42, 61));
        btnCl2.setBorder(null);
        btnCl2.setForeground(new java.awt.Color(255, 255, 255));
        btnCl2.setText("Iced Coffee");
        btnCl2.setBorderColor(new java.awt.Color(27, 31, 43));
        btnCl2.setColor(new java.awt.Color(37, 42, 61));
        btnCl2.setColorClick(new java.awt.Color(235, 87, 87));
        btnCl2.setColorOver(new java.awt.Color(44, 50, 73));
        btnCl2.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnCl2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCl2.setRadius(25);
        btnCl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCl2ActionPerformed(evt);
            }
        });
        jPanel11.add(btnCl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 140, 60));

        q16.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q16.setForeground(new java.awt.Color(235, 87, 87));
        q16.setText("0");
        jPanel11.add(q16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 20, -1));

        btnCl3.setBackground(new java.awt.Color(37, 42, 61));
        btnCl3.setBorder(null);
        btnCl3.setForeground(new java.awt.Color(255, 255, 255));
        btnCl3.setText("Blue Mojito");
        btnCl3.setBorderColor(new java.awt.Color(27, 31, 43));
        btnCl3.setColor(new java.awt.Color(37, 42, 61));
        btnCl3.setColorClick(new java.awt.Color(235, 87, 87));
        btnCl3.setColorOver(new java.awt.Color(44, 50, 73));
        btnCl3.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnCl3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCl3.setRadius(25);
        btnCl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCl3ActionPerformed(evt);
            }
        });
        jPanel11.add(btnCl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 160, 60));

        q17.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q17.setForeground(new java.awt.Color(235, 87, 87));
        q17.setText("0");
        jPanel11.add(q17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 20, -1));

        btnCl4.setBackground(new java.awt.Color(37, 42, 61));
        btnCl4.setBorder(null);
        btnCl4.setForeground(new java.awt.Color(255, 255, 255));
        btnCl4.setText("Black Mojito");
        btnCl4.setBorderColor(new java.awt.Color(27, 31, 43));
        btnCl4.setColor(new java.awt.Color(37, 42, 61));
        btnCl4.setColorClick(new java.awt.Color(235, 87, 87));
        btnCl4.setColorOver(new java.awt.Color(44, 50, 73));
        btnCl4.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnCl4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCl4.setRadius(25);
        btnCl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCl4ActionPerformed(evt);
            }
        });
        jPanel11.add(btnCl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 140, 60));

        q18.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q18.setForeground(new java.awt.Color(235, 87, 87));
        q18.setText("0");
        jPanel11.add(q18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 20, -1));

        btnCl5.setBackground(new java.awt.Color(37, 42, 61));
        btnCl5.setBorder(null);
        btnCl5.setForeground(new java.awt.Color(255, 255, 255));
        btnCl5.setText("Black Currant Mojito");
        btnCl5.setBorderColor(new java.awt.Color(27, 31, 43));
        btnCl5.setColor(new java.awt.Color(37, 42, 61));
        btnCl5.setColorClick(new java.awt.Color(235, 87, 87));
        btnCl5.setColorOver(new java.awt.Color(44, 50, 73));
        btnCl5.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnCl5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCl5.setRadius(25);
        btnCl5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCl5ActionPerformed(evt);
            }
        });
        jPanel11.add(btnCl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 200, 60));

        q19.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        q19.setForeground(new java.awt.Color(235, 87, 87));
        q19.setText("0");
        jPanel11.add(q19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 20, -1));

        btnCl6.setBackground(new java.awt.Color(37, 42, 61));
        btnCl6.setBorder(null);
        btnCl6.setForeground(new java.awt.Color(255, 255, 255));
        btnCl6.setText("Chocolate Milk Shake");
        btnCl6.setBorderColor(new java.awt.Color(27, 31, 43));
        btnCl6.setColor(new java.awt.Color(37, 42, 61));
        btnCl6.setColorClick(new java.awt.Color(235, 87, 87));
        btnCl6.setColorOver(new java.awt.Color(44, 50, 73));
        btnCl6.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        btnCl6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCl6.setRadius(25);
        btnCl6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCl6ActionPerformed(evt);
            }
        });
        jPanel11.add(btnCl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 200, 60));

        jTabbedPane2.addTab("tab2", jPanel11);

        jPanel2.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 660, 630));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(27, 31, 43));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(235, 87, 87));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 5));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 100, 12));

        tblHistory.setFont(new java.awt.Font("Google Sans Medium", 0, 12)); // NOI18N
        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill No.", "Date", "Items", "Bill Amount"
            }
        ));
        tblHistory.setRowHeight(25);
        jScrollPane3.setViewportView(tblHistory);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 107, 910, 470));

        lblFood1.setFont(new java.awt.Font("Google Sans Medium", 0, 24)); // NOI18N
        lblFood1.setForeground(new java.awt.Color(235, 87, 87));
        lblFood1.setText("Orders History");
        jPanel3.add(lblFood1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 260, 50));

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(27, 31, 43));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(235, 87, 87));
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 5));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 100, 12));

        tblBvrg.setBackground(new java.awt.Color(27, 31, 43));
        tblBvrg.setFont(new java.awt.Font("Google Sans Medium", 0, 12)); // NOI18N
        tblBvrg.setForeground(new java.awt.Color(255, 255, 255));
        tblBvrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price"
            }
        ));
        tblBvrg.setGridColor(new java.awt.Color(27, 31, 43));
        tblBvrg.setRowHeight(25);
        tblBvrg.setSelectionBackground(new java.awt.Color(235, 87, 87));
        tblBvrg.setSelectionForeground(new java.awt.Color(27, 31, 43));
        tblBvrg.setShowHorizontalLines(true);
        tblBvrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBvrgMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBvrg);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 495, 180));

        jLabel16.setFont(new java.awt.Font("Google Sans Medium", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Search ");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 50, 20));

        jPanel14.setBackground(new java.awt.Color(37, 42, 61));
        jPanel14.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Name");
        jPanel14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 81, -1));

        jLabel15.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Price");
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 51, -1));

        txtUpdtPrice.setBackground(new java.awt.Color(27, 31, 43));
        txtUpdtPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtUpdtPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUpdtPrice.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        txtUpdtPrice.setRound(25);
        jPanel14.add(txtUpdtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 260, -1));

        txtUpdtName.setBackground(new java.awt.Color(27, 31, 43));
        txtUpdtName.setForeground(new java.awt.Color(255, 255, 255));
        txtUpdtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUpdtName.setEnabled(false);
        txtUpdtName.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        txtUpdtName.setRound(25);
        jPanel14.add(txtUpdtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, -1));

        btnUpdate.setForeground(new java.awt.Color(27, 31, 43));
        btnUpdate.setText("Update");
        btnUpdate.setBorderColor(new java.awt.Color(37, 42, 61));
        btnUpdate.setColor(new java.awt.Color(235, 87, 87));
        btnUpdate.setColorClick(new java.awt.Color(231, 54, 54));
        btnUpdate.setColorOver(new java.awt.Color(238, 118, 118));
        btnUpdate.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        btnUpdate.setRadius(25);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel14.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 240, 40));

        txtUpdtID.setBackground(new java.awt.Color(27, 31, 43));
        txtUpdtID.setForeground(new java.awt.Color(255, 255, 255));
        txtUpdtID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUpdtID.setEnabled(false);
        txtUpdtID.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        txtUpdtID.setRound(25);
        jPanel14.add(txtUpdtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 260, -1));

        jLabel18.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ID");
        jPanel14.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 81, -1));

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 320, 660));

        txtSrchBv.setBackground(new java.awt.Color(37, 42, 61));
        txtSrchBv.setForeground(new java.awt.Color(255, 255, 255));
        txtSrchBv.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        txtSrchBv.setRound(25);
        txtSrchBv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSrchBvKeyReleased(evt);
            }
        });
        jPanel4.add(txtSrchBv, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 210, -1));

        tblFd.setBackground(new java.awt.Color(27, 31, 43));
        tblFd.setFont(new java.awt.Font("Google Sans Medium", 0, 12)); // NOI18N
        tblFd.setForeground(new java.awt.Color(255, 255, 255));
        tblFd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Price"
            }
        ));
        tblFd.setGridColor(new java.awt.Color(27, 31, 43));
        tblFd.setRowHeight(25);
        tblFd.setSelectionBackground(new java.awt.Color(235, 87, 87));
        tblFd.setSelectionForeground(new java.awt.Color(27, 31, 43));
        tblFd.setShowGrid(false);
        tblFd.setShowHorizontalLines(true);
        tblFd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFdMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblFd);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 495, 190));

        txtSrchfd1.setBackground(new java.awt.Color(37, 42, 61));
        txtSrchfd1.setForeground(new java.awt.Color(255, 255, 255));
        txtSrchfd1.setFont(new java.awt.Font("Google Sans Medium", 0, 14)); // NOI18N
        txtSrchfd1.setRound(25);
        txtSrchfd1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSrchfd1KeyReleased(evt);
            }
        });
        jPanel4.add(txtSrchfd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 210, -1));

        jLabel17.setFont(new java.awt.Font("Google Sans Medium", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Search ");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 50, 20));

        jLabel6.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(235, 87, 87));
        jLabel6.setText("Beverages");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 110, 20));

        jLabel7.setFont(new java.awt.Font("Google Sans Medium", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(235, 87, 87));
        jLabel7.setText("Foods");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 110, 20));

        jTabbedPane1.addTab("tab3", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void customTable(){
        tblOrder.getColumnModel().getColumn(0).setPreferredWidth(140);
        tblOrder.getColumnModel().getColumn(1).setPreferredWidth(35);
        tblOrder.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblOrder.getColumnModel().getColumn(3).setPreferredWidth(60);  
    }
    
    private void roundCorners(){
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 25, 25));   
    }
    
    public void curDate(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd / MM / yyyy");
        LocalDateTime now = LocalDateTime.now();
        lblDate.setText(dtf.format(now));
    }
    
    public void setBillNo(){
        CafeModel billObj = new CafeModel();
        CafeController cCb = new CafeController();
        cCb.setBillNo(billObj);
        
        int i = billObj.getBillNo();
        i=i+1;
        lblBillNo.setText(String.valueOf(i));
    }
    
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnUpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatesActionPerformed
        
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnUpdatesActionPerformed

    private void btnFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoodActionPerformed
        btnBeverage.setBorderColor(new Color(27,31,43));
        btnFood.setBorderColor(new Color(235,87,87));
        
        jTabbedPane2.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnFoodActionPerformed

    private void btnBeverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeverageActionPerformed
        btnFood.setBorderColor(new Color(27,31,43));
        btnBeverage.setBorderColor(new Color(235,87,87));
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_btnBeverageActionPerformed

    private void btnHtDg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtDg1ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select fdPrice from foods where fdID=1";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.fdItemAdd(tblObj);
        
        int i= Integer.parseInt(q1.getText());
        ++i;
        q1.setText(String.valueOf(i));
        
        addTable("Chicken Hot Dog",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnHtDg1ActionPerformed

    private void btnHtDg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtDg2ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select fdPrice from foods where fdID=2";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.fdItemAdd(tblObj);
        
        int i= Integer.parseInt(q2.getText());
        ++i;
        q2.setText(String.valueOf(i));
        
        addTable("Egg Wrapped Chicken Hot Dog",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnHtDg2ActionPerformed

    private void btnHtDg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtDg3ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select fdPrice from foods where fdID=3";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.fdItemAdd(tblObj);
        
        int i= Integer.parseInt(q3.getText());
        ++i;
        q3.setText(String.valueOf(i));
        
        addTable("Monster Double Hot Dog",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
        
    }//GEN-LAST:event_btnHtDg3ActionPerformed

    private void btnHtDg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtDg4ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select fdPrice from foods where fdID=4";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.fdItemAdd(tblObj);
        
        int i= Integer.parseInt(q4.getText());
        ++i;
        q4.setText(String.valueOf(i));
        
        addTable("Cheesy Chicken Hot Dog",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnHtDg4ActionPerformed

    private void btnBrgr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrgr1ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select fdPrice from foods where fdID=5";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.fdItemAdd(tblObj);
        
        int i= Integer.parseInt(q5.getText());
        ++i;
        q5.setText(String.valueOf(i));
        
        addTable("Vegetable Burger",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnBrgr1ActionPerformed

    private void btnBrgr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrgr2ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select fdPrice from foods where fdID=6";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.fdItemAdd(tblObj);
        
        int i= Integer.parseInt(q6.getText());
        ++i;
        q6.setText(String.valueOf(i));
        
        addTable("Cheesy Vegetable Burger",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnBrgr2ActionPerformed

    private void btnBrgr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrgr3ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select fdPrice from foods where fdID=7";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.fdItemAdd(tblObj);
        
        int i= Integer.parseInt(q7.getText());
        ++i;
        q7.setText(String.valueOf(i));
        
        addTable("Spicy Chicken Burger",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnBrgr3ActionPerformed

    private void btnBrgr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrgr4ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select fdPrice from foods where fdID=8";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.fdItemAdd(tblObj);
        
        int i= Integer.parseInt(q8.getText());
        ++i;
        q8.setText(String.valueOf(i));
        
        addTable("Cheesy Crispy Chicken Burger",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnBrgr4ActionPerformed

    private void btnSbmrn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSbmrn1ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select fdPrice from foods where fdID=9";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.fdItemAdd(tblObj);
        
        int i= Integer.parseInt(q9.getText());
        ++i;
        q9.setText(String.valueOf(i));
        
        addTable("Vegetable Submarine",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnSbmrn1ActionPerformed

    private void btnSbmrn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSbmrn2ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select fdPrice from foods where fdID=10";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.fdItemAdd(tblObj);
        
        int i= Integer.parseInt(q10.getText());
        ++i;
        q10.setText(String.valueOf(i));
        
        addTable("Spicy Submarine",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnSbmrn2ActionPerformed

    private void btnSbmrn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSbmrn3ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select fdPrice from foods where fdID=11";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.fdItemAdd(tblObj);
        
        int i= Integer.parseInt(q11.getText());
        ++i;
        q11.setText(String.valueOf(i));
        
        addTable("Cheesy Crispy Chicken Submarine",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnSbmrn3ActionPerformed

    private void btnHt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHt2ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select bvPrice from beverage where bvID=2";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.bvItemAdd(tblObj);
        
        int i= Integer.parseInt(q13.getText());
        ++i;
        q13.setText(String.valueOf(i));
        
        addTable("Nescafe",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnHt2ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        btnLogout.setForeground(new Color(37,42,61)); 
        dispose();
        LoginForm login = new LoginForm();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnItmDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItmDeleteActionPerformed
        DefaultTableModel dt = (DefaultTableModel)tblOrder.getModel();
        String r = dt.getValueAt(tblOrder.getSelectedRow(),0).toString();
        
        int selectedRow = tblOrder.getSelectedRow();
        dt.removeRow(selectedRow);
        
        switch(r){
            case "Chicken Hot Dog":
                q1.setText("0");
                break;
            case "Egg Wrapped Chicken Hot Dog":
                q2.setText("0");
                break;
            case "Monster Double Hot Dog":
                q3.setText("0");
                break;
            case "Cheesy Chicken Hot Dog":
                q4.setText("0");
                break;
            case "Vegetable Burger":
                q5.setText("0");
                break;
            case "Cheesy Vegetable Burger":
                q6.setText("0");
                break;
            case "Spicy Chicken Burger":
                q7.setText("0");
                break;
            case "Cheesy Crispy Chicken Burger":
                q8.setText("0");
                break;
            case "Vegetable Submarine":
                q9.setText("0");
                break;
            case "Spicy Submarine":
                q10.setText("0");
                break;
            case "Cheesy Crispy Chicken Submarine":
                q11.setText("0");
                break;
            case "Milo":
                q12.setText("0");
                break;
            case "Nescafe":
                q13.setText("0");
                break;
            case "Orange Juice":
                q14.setText("0");
                break;
            case "Iced Coffee":
                q15.setText("0");
                break;
            case "Blue Mojito":
                q16.setText("0");
                break;
            case "Black Mojito":
                q17.setText("0");
                break;
            case "Black Currant Mojito":
                q18.setText("0");
                break;
            case "Chocolate Milk Shake":
                q19.setText("0");
                break;
                
            default:
        }
        cal();    
    }//GEN-LAST:event_btnItmDeleteActionPerformed

    private void btnItmsClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItmsClearActionPerformed
        OrderClear();
    }//GEN-LAST:event_btnItmsClearActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        double cash = Double.parseDouble(txtCash.getText());
        double tot = Double.parseDouble(lblTot.getText());
        double balance = cash - tot;
        lblBalancetxt.setText(String.valueOf(balance));
        
        CafeModel AddObj = new CafeModel();
        AddObj.setTblOrder(tblOrder);
        AddObj.setDate(lblDate.getText());
        AddObj.setTotal(Double.parseDouble(lblTot.getText()));
        
        CafeController cCt = new CafeController();
        cCt.billToDatabas(AddObj);
        
        viewHistryTbl();
        OrderClear();      
        setBillNo();
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnHt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHt1ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select bvPrice from beverage where bvID=1";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.bvItemAdd(tblObj);
        
        int i= Integer.parseInt(q12.getText());
        ++i;
        q12.setText(String.valueOf(i));
        
        addTable("Milo",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnHt1ActionPerformed

    private void btnCl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCl1ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select bvPrice from beverage where bvID=3";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.bvItemAdd(tblObj);
        
        int i= Integer.parseInt(q14.getText());
        ++i;
        q14.setText(String.valueOf(i));
        
        addTable("Orange Juice",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnCl1ActionPerformed

    private void btnCl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCl2ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select bvPrice from beverage where bvID=4";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.bvItemAdd(tblObj);
        
        int i= Integer.parseInt(q15.getText());
        ++i;
        q15.setText(String.valueOf(i));
        
        addTable("Iced Coffee",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnCl2ActionPerformed

    private void btnCl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCl3ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select bvPrice from beverage where bvID=5";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.bvItemAdd(tblObj);
        
        int i= Integer.parseInt(q16.getText());
        ++i;
        q16.setText(String.valueOf(i));
        
        addTable("Blue Mojito",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnCl3ActionPerformed

    private void btnCl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCl4ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select bvPrice from beverage where bvID=6";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.bvItemAdd(tblObj);
        
        int i= Integer.parseInt(q17.getText());
        ++i;
        q17.setText(String.valueOf(i));
        
        addTable("Black Mojito",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnCl4ActionPerformed

    private void btnCl5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCl5ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select bvPrice from beverage where bvID=7";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.bvItemAdd(tblObj);
        
        int i= Integer.parseInt(q18.getText());
        ++i;
        q18.setText(String.valueOf(i));
        
        addTable("Black Currant Mojito",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnCl5ActionPerformed

    private void btnCl6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCl6ActionPerformed
        CafeModel tblObj = new CafeModel();
        String sql = "select bvPrice from beverage where bvID=8";
        tblObj.setSqlQuery(sql);
        
        CafeController cC = new CafeController();
        cC.bvItemAdd(tblObj);
        
        int i= Integer.parseInt(q19.getText());
        ++i;
        q19.setText(String.valueOf(i));
        
        addTable("Chocolate Milk Shake",i,tblObj.getPrice(),tblObj.getPrice());
        cal();
    }//GEN-LAST:event_btnCl6ActionPerformed

    private void tblFdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFdMouseClicked
        int i = tblFd.getSelectedRow();
        TableModel model=tblFd.getModel();
        txtUpdtID.setText(model.getValueAt(i,0).toString());
        txtUpdtName.setText(model.getValueAt(i,1).toString());
        txtUpdtPrice.setText(model.getValueAt(i,2).toString());
    }//GEN-LAST:event_tblFdMouseClicked

    private void txtSrchfd1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSrchfd1KeyReleased
        DefaultTableModel obj=(DefaultTableModel) tblFd.getModel();
        TableRowSorter<DefaultTableModel> obj1=new TableRowSorter<>(obj);
        tblFd.setRowSorter(obj1);
        obj1.setRowFilter(RowFilter.regexFilter(txtSrchfd1.getText()));
    }//GEN-LAST:event_txtSrchfd1KeyReleased

    private void tblBvrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBvrgMouseClicked
        int i = tblBvrg.getSelectedRow();
        TableModel model=tblBvrg.getModel();
        txtUpdtID.setText(model.getValueAt(i,0).toString());
        txtUpdtName.setText(model.getValueAt(i,1).toString());
        txtUpdtPrice.setText(model.getValueAt(i,2).toString());
    }//GEN-LAST:event_tblBvrgMouseClicked

    private void txtSrchBvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSrchBvKeyReleased
        DefaultTableModel obj=(DefaultTableModel) tblBvrg.getModel();
        TableRowSorter<DefaultTableModel> obj1=new TableRowSorter<>(obj);
        tblBvrg.setRowSorter(obj1);
        obj1.setRowFilter(RowFilter.regexFilter(txtSrchBv.getText()));
    }//GEN-LAST:event_txtSrchBvKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        int fdTableSelected = tblFd.getSelectedRow();
        int bvTableSelected = tblBvrg.getSelectedRow();
        
        if(fdTableSelected != -1){
            CafeModel updateObj = new CafeModel();
            updateObj.setFdId(Integer.parseInt(txtUpdtID.getText()));
            updateObj.setPrice(Double.parseDouble(txtUpdtPrice.getText()));
        
            CafeController cCt = new CafeController();
            cCt.UpdateFdPrice(updateObj);  
        
        }else if(bvTableSelected != -1){
            CafeModel updateObj = new CafeModel();
            updateObj.setBvId(Integer.parseInt(txtUpdtID.getText()));
            updateObj.setPrice(Double.parseDouble(txtUpdtPrice.getText()));
        
            CafeController cCt = new CafeController();
            cCt.UpdateBvPrice(updateObj);
        }
        
        viewFdTbl();
        viewBvTbl();
    }//GEN-LAST:event_btnUpdateActionPerformed
    
    public void viewBillTbl(){
        
        CafeModel viewObj = new CafeModel();
        viewObj.setTblFd(tblFd);
        
        CafeController cCt = new CafeController();
        cCt.getfromDBtoFdTable(viewObj);
    
    }
    
    public void viewHistryTbl(){
        
        CafeModel viewObj = new CafeModel();
        viewObj.setTblHistory(tblHistory);
        
        CafeController cCt = new CafeController();
        cCt.getfromDBtoHistoryTable(viewObj);
    
    }
    
    public void viewFdTbl(){
        
        CafeModel viewObj = new CafeModel();
        viewObj.setTblFd(tblFd);
        
        CafeController cCt = new CafeController();
        cCt.getfromDBtoFdTable(viewObj);
    
    }
    public void viewBvTbl(){
        
        CafeModel viewObj = new CafeModel();
        viewObj.setTblBvrg(tblBvrg);
        
        CafeController cCt = new CafeController();
        cCt.getfromDBtoBvTable(viewObj);
    
    }
    
    public void saveColumnDataToDatabase(JTable table) {
        DefaultTableModel model = (DefaultTableModel) tblOrder.getModel();
        int column = 0; // Index of the column you want to extract data from
        StringBuilder dataBuilder = new StringBuilder();

        // Concatenate data from the specified column
        for (int row = 0; row < model.getRowCount(); row++) {
            Object value = model.getValueAt(row, column);
            if (value != null) {
                dataBuilder.append(value.toString()).append(", ");
            }
        }

        // Remove the trailing comma and space
        String columnData = dataBuilder.toString().trim();
        if (columnData.endsWith(", ")) {
            columnData = columnData.substring(0, columnData.length() - 2);
        }

        // Save the concatenated data to a single cell in the database table
        try 
        {
          Connection connObj = DatabaseConnection.getConnection();
          String sql = "INSERT INTO items (items) VALUES (?)";
          PreparedStatement statement = connObj.prepareStatement(sql);
          statement.setString(1, columnData);
          statement.executeUpdate();  
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    
    
    public void OrderClear(){
        q1.setText("0");
        q2.setText("0");
        q3.setText("0");
        q4.setText("0");
        q5.setText("0");
        q6.setText("0");
        q7.setText("0");
        q8.setText("0");
        q9.setText("0");
        q10.setText("0");
        q11.setText("0");
        q12.setText("0");
        q13.setText("0");
        q14.setText("0");
        q15.setText("0");
        q16.setText("0");
        q17.setText("0");
        q18.setText("0");
        q19.setText("0");
        lblTot.setText("0.00");
        txtCash.setText(" ");
        lblBalancetxt.setText("0.00");
        
        DefaultTableModel dt = (DefaultTableModel)tblOrder.getModel();
        dt.setRowCount(0);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.Buttons btnBeverage;
    private view.Buttons btnBrgr1;
    private view.Buttons btnBrgr2;
    private view.Buttons btnBrgr3;
    private view.Buttons btnBrgr4;
    private view.Buttons btnCl1;
    private view.Buttons btnCl2;
    private view.Buttons btnCl3;
    private view.Buttons btnCl4;
    private view.Buttons btnCl5;
    private view.Buttons btnCl6;
    private view.Buttons btnFood;
    private view.Buttons btnHistory;
    private view.Buttons btnHt1;
    private view.Buttons btnHt2;
    private view.Buttons btnHtDg1;
    private view.Buttons btnHtDg2;
    private view.Buttons btnHtDg3;
    private view.Buttons btnHtDg4;
    private view.Buttons btnItmDelete;
    private view.Buttons btnItmsClear;
    private view.Buttons btnLogout;
    private view.Buttons btnMenu;
    private view.Buttons btnPlaceOrder;
    private view.Buttons btnSbmrn1;
    private view.Buttons btnSbmrn2;
    private view.Buttons btnSbmrn3;
    private view.Buttons btnUpdate;
    private view.Buttons btnUpdates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblBalance1;
    private javax.swing.JLabel lblBalancetxt;
    private javax.swing.JLabel lblBeverage;
    private javax.swing.JLabel lblBillNo;
    private javax.swing.JLabel lblCash1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblFood1;
    private javax.swing.JLabel lblTot;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q10;
    private javax.swing.JLabel q11;
    private javax.swing.JLabel q12;
    private javax.swing.JLabel q13;
    private javax.swing.JLabel q14;
    private javax.swing.JLabel q15;
    private javax.swing.JLabel q16;
    private javax.swing.JLabel q17;
    private javax.swing.JLabel q18;
    private javax.swing.JLabel q19;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel q4;
    private javax.swing.JLabel q5;
    private javax.swing.JLabel q6;
    private javax.swing.JLabel q7;
    private javax.swing.JLabel q8;
    private javax.swing.JLabel q9;
    private javax.swing.JTable tblBvrg;
    private javax.swing.JTable tblFd;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTable tblOrder;
    private view.TextField txtCash;
    private view.TextField txtSrchBv;
    private view.TextField txtSrchfd1;
    private view.TextField txtUpdtID;
    private view.TextField txtUpdtName;
    private view.TextField txtUpdtPrice;
    // End of variables declaration//GEN-END:variables

}
